name: Deploy Backend Prod
on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/backend-prod.yml
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    container:
      image: jmahbubani/natto-server:2022-04-04
      ports:
        - 8080
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set OPENAI_KEY=${{ secrets.OPENAI_KEY }} GCP_CRED_JSON_BASE64=${{ secrets.GCP_CRED_JSON_BASE64 }} -t ${{ secrets.FLY_API_TOKEN_NATTO }} --config ./fly.production.toml
      - run: flyctl deploy --remote-only -t ${{ secrets.FLY_API_TOKEN_NATTO }} --config ./fly.production.toml
        env:
          FLYCTL_AUTH_TOKEN: ${{ secrets.FLY_API_TOKEN_NATTO }} # no longer necessary with -t flag?